version: "3.7"

services:
  web:
    build: .
    command: sh -c "npm ci && npm run develop --host=0.0.0.0"
    ports:
      - "8100:8000"
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules

volumes:
  web_node_modules:
