version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gatsby develop --host=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
