version: "3.7"

services:
  web:
    build: .
    command: sh -c "yarn --pure-lockfile && yarn develop -H 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules

volumes:
  web_node_modules: